#ifndef PROJECT_RENDER_MAX_LIVELINK_RESOURCE_H
#define PROJECT_RENDER_MAX_LIVELINK_RESOURCE_H

#define IDD_LIVELINK_UTILITY 101
#define IDC_LIVELINK_STATUS 1001
#define IDC_LIVELINK_START 1002
#define IDC_LIVELINK_STOP 1003

#endif